#!/bin/bash

ARTIST=`ls /tmp/ramdisk`
ALBUM=`ls "/tmp/ramdisk/$ARTIST"`
ARTIST_NO_SPACES=`echo "$ARTIST" | tr [:blank:] . | sed "s_'_\xe2\x80\x99_"`
ALBUM_NO_SPACES=`echo "$ALBUM" | tr [:blank:] . | sed "s_'_\xe2\x80\x99_"`

REMOTE_DIRECTORY=/volume1/music/flac/$ARTIST_NO_SPACES-$ALBUM_NO_SPACES
echo "Creating remote directory: [$REMOTE_DIRECTORY]."
read -p "Is this ok? " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
    exit 1;
fi
echo

ssh vault -x "mkdir $REMOTE_DIRECTORY"
echo "Copying files to remote directory."
STORE_IFS=$IFS
IFS=$(echo -e "\r")
for i in /tmp/ramdisk/*/*/*;
do
    scp $i vault:$REMOTE_DIRECTORY;
done
IFS=$STORE_IFS
ssh vault -x "for i in $REMOTE_DIRECTORY/*; do echo \"Adding \"\$i\" to index.\"; synoindex -a \"\$i\"; done"

exit 0

